spring:
  application:
    name: real-time-learderboard

# Logging Configuration
logging:
  level:
    # Root level
    root: INFO
    # Application specific
    com.hackathon.realtimelearderboard: DEBUG
    # Spring framework
    org.springframework.web: DEBUG
    org.springframework.security: INFO
    org.springframework.data.redis: DEBUG
    # Redis operations
    io.lettuce: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/real-time-learderboard.log
    max-size: 100MB
    max-history: 30

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true
  metrics:
    export:
      simple:
        enabled: true